### ISSUE TITLE
To do

### ISSUE THREAD

**Issue by AnthonyMaz** [AnthonyMaz/pyfileOrganize#1]
compare shasum files in list to other files in list

**Comment by HillaFPV** [comment]
sha1 might be suitable, but if it's taking too long to run I'd say md5 is fine in this case

**Comment by AnthonyMaz** [comment]
Closing issue. Moving original repo files to new repo bashfileOrganize . Renaming this repo to pyfileOrganize.

**Comment by AnthonyMaz** [comment]
Closing issue. Moving original repo files to new repo bashfileOrganize . Renaming this repo to pyfileOrganize.
