### ISSUE TITLE
File Types

### ISSUE THREAD

**Issue by HillaFPV** [AnthonyMaz/pyfileOrganize#2]
https://github.com/AnthonyMaz/fileOrganize/blob/5f0937f536f061be427ad2b98a3143f2fad01cc1/fileorg.sh#L7

This is going to compare extensions, which may not be exhaustive or even accurate (if a .txt file is renamed to .mp4 it'll be a false positive)

Consider using `file --mime-type` and the file's headers will be inspected to get the actual file type. You can parse that out to organize files by their actual type.

**Comment by AnthonyMaz** [comment]
Closing issue. Moving original repo files to new repo bashfileOrganize . Renaming this repo to pyfileOrganize.
